### ISSUE TITLE
Error when running the applications

### ISSUE THREAD

**Issue by fjvallarino** [gvolpe/fts#2]
Hi! 

I'm not too familiar with Nix, so this is probably an issue on my end. I'm running Ubuntu 21.04 inside VMWare, installing Nix using the standard installation script, and Docker with the corresponding official instructions. I also installed Cachix and followed the instructions on this repository.

Everything was built successfully, and the Docker instance is running fine, but both the console and UI programs fail to start. Do I have to run the programs using some specific Nix command? I tried running them as regular applications. The console version outputs:

```
fts: <stdout>: commitBuffer: invalid argument (invalid character)
```

While the UI version shows:

```
Invalid window
fts-ui: SDLCallFailed {sdlExceptionCaller = "SDL.Video.glCreateContext", sdlFunction = "SDL_GL_CreateContext", sdlExceptionError = "Invalid window"}
```

This is the same virtual machine I use for testing Monomer; that's what makes me think I may be missing something related to Nix.

Thanks!

**Comment by gvolpe** [comment]
Did you build them via `nix-build` and then ran `result/bin/fts-ui`? It could be that the SDL library is missing and needs to be declared explicitly in the `default.nix` file, but I'm really surprised to hear the console application errors out.

I will try to run the project in a VM from scratch tomorrow as now it's a bit late on my end. I'll report back.

**Comment by fjvallarino** [comment]
Yes! I ran this:

```shell
$ cachix use fts
$ nix-build
```

And then tried `./result/bin/fts` and `./result/bin/fts-ui` (also tried running the applications from the ``./result/bin/` directory).

**Comment by gvolpe** [comment]
I managed to reproduce the issue in a VM with Ubuntu but then I ran into other software issues, and I ran out of free time today. 

```
fts: <stdout>: commitBuffer: invalid argument (invalid character)
```

The console app issue seems to be related to `freetype` not being available, needed to render some emojis and unicode chars.

```
Invalid window
fts-ui: SDLCallFailed {sdlExceptionCaller = "SDL.Video.glCreateContext", sdlFunction = "SDL_GL_CreateContext", sdlExceptionError = "Invalid window"}
```

The GUI app fails because SDL does not seem available but I don't know how to fix it yet for other platforms.

---

Can you try https://github.com/gvolpe/fts/pull/3? Not sure if this is going to work but it's worth a try. I can try to dig in during the weeked, now my VM is completely screwed after installing some stuff via `sudo apt install` 😏

**Comment by gvolpe** [comment]
You can also try entering `nix-shell` and then `cabal new-run fts-ui` but I experienced the same issue in my VM.

**Comment by fjvallarino** [comment]
I just tried with the branch's code and got the same error in the console version. The same happens with nix-shell.

On the UI side, it seems the issue is related to OpenGL drivers. Installing [nixGL](https://github.com/guibou/nixGL) solved the problem for me.

It looks awesome! Thanks!

**Comment by gvolpe** [comment]
Yeah it seems we arrived at the same place, I was about to suggest [nixGL](https://github.com/guibou/nixGL) as well, I got it working on Ubuntu with it. I will update the README file with this info, glad you got it working! :)

**Comment by fjvallarino** [comment]
I really liked the combination of Nix and Docker for distributing projects like this.

Thanks for your help!

**Comment by gvolpe** [comment]
Unrelated question: I wasn't able to figure out why, whenever the `TMDB_API_KEY` is not set, the UI only displays a single result, even when there are multiple results and I can see `sendMsg (MoviesSearchResult [s])` is invoked. Maybe you can help? 😄 

![odd](https://i.imgur.com/0G5DkWN.png)

Here's the [MovieRow](https://github.com/gvolpe/fts/blob/main/ui/UI/Widgets/MovieRow.hs#L35) widget and the [Event Handler](https://github.com/gvolpe/fts/blob/main/ui/Handler.hs#L28). When the env var is set, all the results are displayed normally.

![normal](https://i.imgur.com/mgbS37t.png)

Maybe I'm making a really obvious mistake? It's got me puzzled 😆

**Comment by fjvallarino** [comment]
Interesting. I just created the API key and can reproduce the issue.

I'll test a few things since this could be a library issue. When the API key is set, I notice a short delay in the logs since posters are available; I don't see this delay when the API key is not set. Maybe the model is not updated correctly when multiple messages are received on the same cycle (overwriting the previous versions). 

I'll keep you posted!

**Comment by gvolpe** [comment]
Awesome, thanks a lot! (and thanks again for Monomer 😃  )

**Comment by gvolpe** [comment]
It could be what you say, that the model gets multiple messages in such a short time and it doesn't get properly updated.

However, your comment made me realize that when `TMDB_API_KEY` is not set, there's no need to check for its existence multiple times and send movie results one by one, so I fixed this here: https://github.com/gvolpe/fts/commit/87362aa512f2cc2e3d3d4a4738312aacc67c5cc1

**Comment by fjvallarino** [comment]
I can confirm, it's an issue in the library.

I have a fix, but I want to validate/improve my test cases before publishing a new version.

Thanks for finding this issue!
